# Generated by Django 3.0.5 on 2020-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200501_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='fooAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about1', models.TextField()),
                ('about2', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='main',
            name='about',
        ),
    ]
