# Generated by Django 3.0.5 on 2020-05-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200501_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.SlugField(max_length=20),
        ),
    ]
