# Generated by Django 3.0.5 on 2020-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200501_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooabout',
            name='telephone',
            field=models.TextField(default='+880'),
        ),
    ]
