# Generated by Django 3.0.5 on 2020-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fooabout_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooabout',
            name='telephone',
            field=models.TextField(default='(+880)'),
        ),
    ]
