# Generated by Django 3.0.5 on 2020-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200501_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooabout',
            name='brif_about',
            field=models.TextField(default='-'),
        ),
    ]
