# Generated by Django 3.0.5 on 2020-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='about_first',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_second',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_third',
            field=models.TextField(default='-'),
        ),
    ]
