# Generated by Django 3.0.5 on 2020-05-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200504_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='about_main',
        ),
    ]
